trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    displayName: "Checkout repository code"

  - script: |
      npm install
    displayName: "Install dependencies"

  - script: |
      npx playwright install
    displayName: "Install Playwright"

  - script: |
      npx playwright test
    displayName: "Run Playwright tests"

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: './playwright-report'
      artifactName: 'test-results'
    displayName: "Save test results as artifact"

